const $=s=>document.querySelector(s);
const S='studyforge', subjects=SUBJECTS;
let st=JSON.parse(localStorage[S]||'null')||{xp:0,streak:0,subject:subjects[0],level:'Lycée',goal:'Maîtriser',time:'30 min',m:{}};
let mode='prof',qi=0;
subjects.forEach(x=>{let o=document.createElement('option');o.textContent=x;$('#subject').append(o)});
const data=LESSONS;
const save=()=>localStorage[S]=JSON.stringify(st);
const ms=id=>st.m[id]||0;
function home(){let a=data[st.subject], avg=a.reduce((q,x,i)=>q+ms(st.subject+i),0)/a.length;$('#title').textContent=a.map(x=>x[0]).join(' · ');$('#sub').textContent=`${st.level} · ${st.goal} · ${st.time}/jour`;$('#xp') .textContent=st.xp+' XP';$('#mastery').textContent=Math.round(avg*100)+'%';$('#streak').textContent=st.streak+' j';$('#count').textContent=a.length;$('#plan').innerHTML=a.map((x,i)=>`<div class="item"><b>${x[0]}</b><div>${Math.round(ms(st.subject+i)*100)}% maîtrisé</div><div class="progress"><i style="width:${ms(st.subject+i)*100}%"></i></div></div>`).join('')}
function show(id){document.querySelectorAll('main>section').forEach(x=>x.hidden=true);$('#'+id).hidden=false;if(id==='home')home();if(id==='course')course();if(id==='practice')practice();if(id==='quiz')quiz();if(id==='secrets')secrets();if(id==='chat')chatInit()}
function course(){$('#courseBox').innerHTML='<div class="card"><h2>Cours adaptatif</h2>'+data[st.subject].map((x,i)=>`<article class="item"><h3>${i+1}. ${x[0]}</h3><p>${x[1]}</p><p><b>Exercice :</b> ${x[2]}</p><small>Maîtrise : ${Math.round(ms(st.subject+i)*100)}% — progression vers transfert/inédit après consolidation.</small></article>`).join('')+'</div>'}
function practice(){let a=data[st.subject],i=0;for(let j=1;j<a.length;j++)if(ms(st.subject+j)<ms(st.subject+i))i=j;let x=a[i];$('#practiceBox').innerHTML=`<div class="card"><small>EXERCICE ADAPTATIF</small><h2>${x[0]}</h2><p>${x[2]}</p><textarea id="ans" rows="5" placeholder="Écris ton raisonnement…"></textarea><br><button id="done">J'ai terminé</button><div id="fb"></div></div>`;$('#done').onclick=()=>{st.m[st.subject+i]=Math.min(1,ms(st.subject+i)+.12);st.xp+=20;st.streak=Math.max(1,st.streak);save();$('#fb').innerHTML='<div class="item">Résultat enregistré. La version connectée pourra analyser les étapes de ton raisonnement et classer les erreurs.</div>'}}
function quiz(){let a=data[st.subject],i=qi%a.length,x=a[i];$('#quizBox').innerHTML=`<div class="card"><small>QUIZ ADAPTATIF</small><h2>${x[0]}</h2><p>${x[2]}</p><div class="chips"><button data-q="1">Je maîtrise</button><button data-q=".04">Partiellement</button><button data-q="-.08">Je bloque</button></div></div>`;document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{let d=+b.dataset.q;st.m[st.subject+i]=Math.max(0,Math.min(1,ms(st.subject+i)+d));st.xp+=d>.1?25:10;qi++;save();quiz()})}
function secrets(){let all=['Lire les contraintes avant de calculer.','Tester une méthode sur un cas simple.','Chercher la structure avant la formule.','Localiser précisément l’étape d’une erreur.','Varier la forme pour vérifier le transfert.'];let n=Math.floor(st.xp/100);$('#secretBox').innerHTML='<div class="card"><h2>Secrets pédagogiques</h2>'+all.map((x,i)=>`<div class="item">${i<n?'🔓':'🔒'} ${i<n?x:'Débloqué à '+((i+1)*100)+' XP'}</div>`).join('')+'</div>'}
function chatInit(){if($('#messages').children.length)return;$('#messages').innerHTML='<div class="bubble">Je suis Araphax. En local, cette interface est une démonstration. En production, elle peut appeler le backend /api/chat sans exposer la clé IA.</div>'}
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>show(b.dataset.page));document.querySelectorAll('.back').forEach(b=>b.onclick=()=>show('home'));
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$('#messages').insertAdjacentHTML('beforeend',`<div class="bubble">Mode ${mode} activé.</div>`)});
$('#send').onclick=()=>{let v=$('#msg').value.trim();if(!v)return;$('#messages').insertAdjacentHTML('beforeend',`<div class="bubble me">${v.replaceAll('<','&lt;')}</div><div class="bubble">Démo locale : le backend réel répondra ici.</div>`);$('#msg').value=''};
$('#start').onclick=()=>{st.level=$('#level').value;st.subject=$('#subject').value;st.goal=$('#goal').value;st.time=$('#time').value;st.streak=Math.max(1,st.streak);save();$('#setup').hidden=true;show('home')};
let sec=1500,t=null;function clock(){let m=String(Math.floor(sec/60)).padStart(2,'0'),s=String(sec%60).padStart(2,'0');$('#timer').textContent=m+':'+s}clock();$('#timerBtn').onclick=()=>{if(t){clearInterval(t);t=null;$('#timerBtn').textContent='Reprendre'}else{t=setInterval(()=>{if(sec){sec--;clock()}else clearInterval(t)},1000);$('#timerBtn').textContent='Pause'}};
if(localStorage[S]){$('#setup').hidden=true;show('home')}if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');